app:
  bounded-context: bd1
  microservice: order
  sub-domain: sub1
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: ${app.port:11000}
  tomcat:
    threads:
      max: 200
      min-spare: 50
    max-connections: 500
    max-keep-alive-requests: 200
    keep-alive-timeout: 120s
    max-swallow-size: 4000
spring:
  application:
    name: order
  cloud:
    loadbalancer:
      retry:
        avoid-previous-instance: true
        enabled: true
        max-retries-on-next-service-instance: 2
        max-retries-on-same-service-instance: 0
        retry-on-all-operations: true
  config:
    import: configserver:http://127.0.0.1:8888
resilience4j:
  retry:
    metrics:
      enabled: true
    instances:
      restaurantretry:
        max-attempts: 2
        retry-exception-predicate: com.training.spring.order.integrations.restaurant.MyRetryExceptionPredicate
        result-predicate: com.training.spring.order.integrations.restaurant.RestaurantMenuResultPredicate
  circuitbreaker:
    metrics:
      enabled: true
    instances:
      cbrestaurant:
        sliding-window-type: count-based
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: false
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 2000
        slow-call-rate-threshold: 40
          