app:
  bounded-context: bd2
  microservice: restaurant
  sub-domain: sub1
server:
  port: ${app.port:10000}
  tomcat:
    threads:
      max: 200
      min-spare: 50
    max-connections: 500
    max-keep-alive-requests: 200
    keep-alive-timeout: 120s
    max-swallow-size: 4000
spring:
  application:
    name: restaurant
  config:
    import: configserver:http://127.0.0.1:8888
